export const connectedTwoWords = [
  ['India', 'New Delhi'],
  ['Indonesia', 'Jakarta'],
  ['Iran', 'Tehran'],
  ['Iraq', 'Baghdad'],
  ['Ireland', 'Dublin'],
  ['Israel', 'Jerusalem'],
  ['Italy', 'Rome'],
  ['Jamaica', 'Kingston'],
  ['Japan', 'Tokyo'],
  ['Jordan', 'Amman'],
  ['Kazakhstan', 'Nur-Sultan'],
  ['Kenya', 'Nairobi'],
  ['Kiribati', 'South Tarawa'],
  ['Kuwait', 'Kuwait City'],
  ['Kyrgyzstan', 'Bishkek'],
  ['Laos', 'Vientiane'],
  ['Latvia', 'Riga'],
  ['Lebanon', 'Beirut'],
  ['Lesotho', 'Maseru'],
  ['Liberia', 'Monrovia'],
  ['Libya', 'Tripoli'],
  ['Liechtenstein', 'Vaduz'],
  ['Lithuania', 'Vilnius'],
  ['Madagascar', 'Antananarivo'],
  ['Malawi', 'Lilongwe'],
  ['Malaysia', 'Kuala Lumpur'],
  ['Maldives', 'Malé'],
  ['Mali', 'Bamako'],
  ['Malta', 'Valletta'],
  ['Mauritania', 'Nouakchott'],
  ['Mauritius', 'Port Louis'],
  ['Mexico', 'Mexico City'],
  // Additional data for two-word pairs
  ['Argentina', 'Buenos Aires'],
  ['Australia', 'Canberra'],
  ['Brazil', 'Brasília'],
  ['Canada', 'Ottawa'],
  ['China', 'Beijing'],
  ['France', 'Paris'],
  ['Germany', 'Berlin'],
  ['Russia', 'Moscow'],
  ['South Korea', 'Seoul'],
  ['United Kingdom', 'London'],
];

export const connectedThreeWords = [
  ['Basil', 'Thyme', 'Rosemary'],
  ['Latte', 'Cappuccino', 'Espresso'],
  ['Octopus', 'Dolphin', 'Seahorse'],
  ['Beach', 'Mountain', 'Forest'],
  ['Paintbrush', 'Canvas', 'Palette'],
  ['Rock', 'Pop', 'Jazz'],
  ['Running', 'Yoga', 'Dancing'],
  ['Volcano', 'Canyon', 'Ocean'],
  ['Phone', 'Email', 'Letter'],
  ['Flood', 'Earthquake', 'Hurricane'],
  ['Sight', 'Smell', 'Taste'],
  ['Past', 'Present', 'Future'],
  ['Literature', 'History', 'Biology'],
  ['Spring', 'Summer', 'Autumn'],
  ['Basketball', 'Jersey', 'Whistle'],
  ['Textbook', 'Notebook', 'Pencil'],
  ['Spoon', 'Fork', 'Knife'],
  ['Shirt', 'Pants', 'Shoes'],
  ['Lion', 'Elephant', 'Giraffe'],
  ['Sunflower', 'Rose', 'Daisy'],
  ['Cucumber', 'Tomato', 'Carrot'],
  ['Tea', 'Coffee', 'Juice'],
  ['Milk', 'Yogurt', 'Cheese'],
  ['Pikachu', 'Charmander', 'Squirtle'],
  ['Batman', 'Superman', 'Spiderman'],
  ['Elsa', 'Anna', 'Olaf'],
  // Additional data for three-word pairs
  ['Dog', 'Cat', 'Rabbit'],
  ['Red', 'Blue', 'Green'],
  ['Apple', 'Banana', 'Orange'],
  ['Monday', 'Wednesday', 'Friday'],
  ['Winter', 'Spring', 'Summer'],
  ['Jazz', 'Blues', 'Rock'],
  ['Shovel', 'Spade', 'Fork'],
  ['Bicycle', 'Skateboard', 'Scooter'],
  ['Sushi', 'Tempura', 'Ramen'],
  ['Math', 'Physics', 'Chemistry'],
  ['Tiger', 'Bear', 'Wolf'],
  ['Chocolate', 'Candy', 'Cookies'],
];

export const connectedFourWords = [
  ['Cinnamon', 'Nutmeg', 'Ginger', 'Allspice'],
  ['Guitar', 'Drums', 'Piano', 'Violin'],
  ['Mercury', 'Venus', 'Earth', 'Mars'],
  ['Monday', 'Tuesday', 'Friday', 'Sunday'],
  ['Black', 'White', 'Grey', 'Navy Blue'],
  ['Sun', 'Rain', 'Wind', 'Snow'],
  ['Hand', 'Foot', 'Ear', 'Eye'],
  ['Apple', 'Orange', 'Banana', 'Grape'],
  ['Math', 'English', 'Science', 'History'],
  ['Car', 'Bus', 'Train', 'Airplane'],
  ['Phone', 'Laptop', 'Headset', 'Charger'],
  ['Pen', 'Pencil', 'Eraser', 'Notebook'],
  ['Scarf', 'Hat', 'Gloves', 'Boots'],
  ['Ruler', 'Scissors', 'Calculator', 'Glue'],
  // Additional data for four-word pairs
  ['Chair', 'Table', 'Sofa', 'Bed'],
  ['Tennis', 'Football', 'Basketball', 'Baseball'],
  ['Cup', 'Plate', 'Spoon', 'Fork'],
  ['Laptop', 'Smartphone', 'Tablet', 'Smartwatch'],
  ['Red', 'Blue', 'Yellow', 'Green'],
  ['Tiger', 'Elephant', 'Giraffe', 'Zebra'],
  ['Salt', 'Pepper', 'Olive Oil', 'Vinegar'],
  ['Apple', 'Samsung', 'Huawei', 'OnePlus'],
  ['Chicken', 'Beef', 'Pork', 'Fish'],
  ['Winter', 'Spring', 'Summer', 'Autumn'],
  ['Jazz', 'Rock', 'Pop', 'Classical'],
  ['Carrot', 'Potato', 'Onion', 'Garlic'],
];

export const connectedWords = new Map([
  [2, connectedTwoWords],
  [3, connectedThreeWords],
  [4, connectedFourWords],
]);